"""
Turning a person into a directory name, safely.

The only place in the system where somebody's identifier becomes part of a
path or a collection name, which is why it is also the only place that
validates one.

We generate these identifiers and they cannot contain anything dangerous.
They are validated anyway, because "cannot" is a property of today's
generator and a directory traversal is permanent — the check costs a regular
expression and removes a whole class of mistake from every future change to
how identifiers are made.

Anything that does not match is **refused rather than cleaned up**. Cleaning
turns an invalid identifier into a valid-looking path, which means a person
who should have caused an error instead quietly gets somebody else's
directory, or a new one nobody expected.
"""

from __future__ import annotations

import logging
import re
from pathlib import Path

logger = logging.getLogger(__name__)

# What an identifier may contain. Deliberately narrower than anything a
# filesystem or a collection name would accept: these are generated by us,
# so the pattern describes what we produce rather than what is tolerated.
SAFE_KEY = re.compile(r"^[A-Za-z0-9_-]{1,64}$")

# What a per-person search collection is called.
COLLECTION_PREFIX = "lumen_"


class UnsafeUserKey(ValueError):
    """
    An identifier that must not become a path.

    A refusal rather than a correction. Silently rewriting one into something
    acceptable would hand back a directory for a person who does not exist.
    """


def user_key(user_id: str) -> str:
    """
    The identifier, checked and unchanged.

    Returns exactly what it was given, when what it was given is safe. That
    it changes nothing is the point: a function that returned something
    different would be a second identifier for the same person, and the
    directory somebody's history lives in cannot depend on which one a caller
    happened to use.
    """
    candidate = (user_id or "").strip()
    if not SAFE_KEY.match(candidate):
        logger.warning("an identifier was refused as a store name")
        raise UnsafeUserKey(
            "a user identifier may only contain letters, numbers, dashes and "
            "underscores, and must be between 1 and 64 characters"
        )
    return candidate


def graph_dir(root: str, user_id: str) -> Path:
    """
    Where this person's graph lives.

    Built from a validated key, so nothing here has to think about what a
    path separator or a parent reference would do — neither can be present.
    """
    return Path(root).expanduser() / user_key(user_id)


def collection_name(user_id: str) -> str:
    """What this person's search collection is called."""
    return f"{COLLECTION_PREFIX}{user_key(user_id)}"


def is_ours(name: str) -> bool:
    """
    Whether a collection name is one of ours.

    Used when listing what exists, so a search index shared with something
    else is not mistaken for a person.
    """
    return name.startswith(COLLECTION_PREFIX)


__all__ = [
    "SAFE_KEY",
    "COLLECTION_PREFIX",
    "UnsafeUserKey",
    "user_key",
    "graph_dir",
    "collection_name",
    "is_ours",
]
