"""initial ops schema

Revision ID: 0001
Revises: 
Create Date: 2026-08-04 15:21:16.492154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_erasure_audit',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('user_id_hash', sa.String(length=64), nullable=False),
    sa.Column('erased_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('nodes_anonymized', sa.Integer(), nullable=False),
    sa.Column('embeddings_deleted', sa.Integer(), nullable=False),
    sa.Column('entry_ids_affected', sa.JSON(), nullable=True),
    sa.Column('initiated_by', sa.String(length=48), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_erasure_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_erasure_audit_user_id_hash'), ['user_id_hash'], unique=False)

    op.create_table('session_buffers',
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('session_label', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decayed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('session_id'),
    sa.UniqueConstraint('user_id', 'event_date', 'session_label', name='uq_buffer_user_date_label')
    )
    with op.batch_alter_table('session_buffers', schema=None) as batch_op:
        batch_op.create_index('ix_buffer_status_activity', ['status', 'last_activity_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_buffers_user_id'), ['user_id'], unique=False)

    op.create_table('user_settings',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'key')
    )
    op.create_table('buffer_messages',
    sa.Column('message_id', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=8), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('dialogue_act', sa.String(length=48), nullable=True),
    sa.Column('co_created_marker', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session_buffers.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id'),
    sa.UniqueConstraint('session_id', 'seq', name='uq_message_session_seq')
    )
    with op.batch_alter_table('buffer_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_buffer_messages_session_id'), ['session_id'], unique=False)

    op.create_table('pipeline_jobs',
    sa.Column('job_id', sa.String(length=128), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_stage', sa.String(length=48), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_type', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('config_snapshot', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session_buffers.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id')
    )
    with op.batch_alter_table('pipeline_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_jobs_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_jobs_trace_id'), ['trace_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('hitl_queue',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('job_id', sa.String(length=128), nullable=True),
    sa.Column('audit_node_id', sa.String(length=256), nullable=False),
    sa.Column('observation_id', sa.String(length=256), nullable=True),
    sa.Column('episode_id', sa.String(length=256), nullable=True),
    sa.Column('entry_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority_rank', sa.Integer(), nullable=False),
    sa.Column('signal_rank', sa.Integer(), nullable=False),
    sa.Column('recommended_action', sa.String(length=32), nullable=True),
    sa.Column('candidate_a_node_id', sa.String(length=256), nullable=True),
    sa.Column('candidate_b_node_id', sa.String(length=256), nullable=True),
    sa.Column('confidence_a', sa.Float(), nullable=True),
    sa.Column('confidence_b', sa.Float(), nullable=True),
    sa.Column('context_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('snooze_count', sa.Integer(), nullable=False),
    sa.Column('last_snoozed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_choice', sa.String(length=48), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['pipeline_jobs.job_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_node_id')
    )
    with op.batch_alter_table('hitl_queue', schema=None) as batch_op:
        batch_op.create_index('ix_hitl_priority', ['user_id', 'status', 'priority_rank', 'signal_rank', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_hitl_queue_trace_id'), ['trace_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hitl_queue_user_id'), ['user_id'], unique=False)

    op.create_table('pipeline_stage_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=128), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=48), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.String(length=128), nullable=True),
    sa.Column('validation_passed', sa.Boolean(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('input_payload', sa.JSON(), nullable=True),
    sa.Column('output_payload', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['pipeline_jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'stage', 'attempt', name='uq_stage_run_job_stage_attempt')
    )
    with op.batch_alter_table('pipeline_stage_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_stage_runs_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_stage_runs_trace_id'), ['trace_id'], unique=False)

    op.create_table('pipeline_write_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=128), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=48), nullable=False),
    sa.Column('target', sa.String(length=32), nullable=False),
    sa.Column('node_id', sa.String(length=256), nullable=True),
    sa.Column('edge_type', sa.String(length=128), nullable=True),
    sa.Column('from_id', sa.String(length=256), nullable=True),
    sa.Column('to_id', sa.String(length=256), nullable=True),
    sa.Column('written_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['pipeline_jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pipeline_write_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_write_log_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_write_log_node_id'), ['node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_write_log_trace_id'), ['trace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pipeline_write_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_write_log_trace_id'))
        batch_op.drop_index(batch_op.f('ix_pipeline_write_log_node_id'))
        batch_op.drop_index(batch_op.f('ix_pipeline_write_log_job_id'))

    op.drop_table('pipeline_write_log')
    with op.batch_alter_table('pipeline_stage_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_stage_runs_trace_id'))
        batch_op.drop_index(batch_op.f('ix_pipeline_stage_runs_job_id'))

    op.drop_table('pipeline_stage_runs')
    with op.batch_alter_table('hitl_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hitl_queue_user_id'))
        batch_op.drop_index(batch_op.f('ix_hitl_queue_trace_id'))
        batch_op.drop_index('ix_hitl_priority')

    op.drop_table('hitl_queue')
    with op.batch_alter_table('pipeline_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_pipeline_jobs_trace_id'))
        batch_op.drop_index(batch_op.f('ix_pipeline_jobs_session_id'))

    op.drop_table('pipeline_jobs')
    with op.batch_alter_table('buffer_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_buffer_messages_session_id'))

    op.drop_table('buffer_messages')
    op.drop_table('user_settings')
    with op.batch_alter_table('session_buffers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_buffers_user_id'))
        batch_op.drop_index('ix_buffer_status_activity')

    op.drop_table('session_buffers')
    with op.batch_alter_table('data_erasure_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_erasure_audit_user_id_hash'))

    op.drop_table('data_erasure_audit')
    # ### end Alembic commands ###
